#!/bin/bash
sudo apt update
sudo apt upgrade
sudo apt install bash-completion
cat /etc/profile.d/bash_completion.sh
echo "source /etc/profile.d/bash_completion.sh" >> ~/.bashrc
source /etc/profile.d/bash_completion.sh
